# This is a basic workflow to help you get started with Actions

name: ETH (Etherscan/Web/Goerli)

# Controls when the action will run. 
on:
  schedule:
  # run at 1am every day
  # * is a special character in YAML so you have to quote this string
    - cron:  '0 21,9 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.repository == 'tintinweb/smart-contract-sanctuary'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo - depth 1
        uses: actions/checkout@v2
      
      # setup python 3
      - name: Set up Python 3.8 üêç
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      # install dependencies
      - name: Install dependencies
        run: pip3 install -r requirements.txt
        working-directory: utils

      # Runs a single command using the runners shell
      - name: Dump Contracts (web)
        run: python3 download_etherscan.py -c etherscan.io -n goerli
        working-directory: utils
    
      # commit changes
      - name: Persist changes / autocommit
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'contracts'

          # The name of the user that will be displayed as the author of the commit
          # Default: author of the commit that triggered the run
          author_name: auto/updateContractsEtherscanWebGoerli


          # The message for the commit
          # Default: 'Commit from GitHub Actions (name of the workflow)'
          message: 'auto - updateContractsEtherscanWebGoerli (goerli) - autocommit'
